--
-- PostgreSQL database dump
--

-- Dumped from database version 17.5
-- Dumped by pg_dump version 17.5

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: PilarSalud; Type: SCHEMA; Schema: -; Owner: postgres
--

CREATE SCHEMA "PilarSalud";


ALTER SCHEMA "PilarSalud" OWNER TO postgres;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: Dependencia; Type: TABLE; Schema: PilarSalud; Owner: postgres
--

CREATE TABLE "PilarSalud"."Dependencia" (
    "Id_Dependencia" integer NOT NULL,
    "Id_Localidad" integer,
    "NombreDependencia" character varying
);


ALTER TABLE "PilarSalud"."Dependencia" OWNER TO postgres;

--
-- Name: Dependencia_Id_Dependencia_seq; Type: SEQUENCE; Schema: PilarSalud; Owner: postgres
--

ALTER TABLE "PilarSalud"."Dependencia" ALTER COLUMN "Id_Dependencia" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "PilarSalud"."Dependencia_Id_Dependencia_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Especialidad; Type: TABLE; Schema: PilarSalud; Owner: postgres
--

CREATE TABLE "PilarSalud"."Especialidad" (
    "Id_Especialidad" integer NOT NULL,
    "NombreEspecialidad" character varying
);


ALTER TABLE "PilarSalud"."Especialidad" OWNER TO postgres;

--
-- Name: EspecialidadMedico; Type: TABLE; Schema: PilarSalud; Owner: postgres
--

CREATE TABLE "PilarSalud"."EspecialidadMedico" (
    "Id_EspMedico" integer NOT NULL,
    "Documento" integer,
    "Id_Especialidad" integer
);


ALTER TABLE "PilarSalud"."EspecialidadMedico" OWNER TO postgres;

--
-- Name: EspecialidadMedico_Id_EspMedico_seq; Type: SEQUENCE; Schema: PilarSalud; Owner: postgres
--

ALTER TABLE "PilarSalud"."EspecialidadMedico" ALTER COLUMN "Id_EspMedico" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "PilarSalud"."EspecialidadMedico_Id_EspMedico_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Especialidad_Id_Especialidad_seq; Type: SEQUENCE; Schema: PilarSalud; Owner: postgres
--

ALTER TABLE "PilarSalud"."Especialidad" ALTER COLUMN "Id_Especialidad" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "PilarSalud"."Especialidad_Id_Especialidad_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Fecha; Type: TABLE; Schema: PilarSalud; Owner: postgres
--

CREATE TABLE "PilarSalud"."Fecha" (
    "Id_Fecha" integer NOT NULL,
    "Dia" integer,
    "Mes" integer,
    "Año" integer
);


ALTER TABLE "PilarSalud"."Fecha" OWNER TO postgres;

--
-- Name: Fecha_Id_Fecha_seq; Type: SEQUENCE; Schema: PilarSalud; Owner: postgres
--

ALTER TABLE "PilarSalud"."Fecha" ALTER COLUMN "Id_Fecha" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "PilarSalud"."Fecha_Id_Fecha_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Indica; Type: TABLE; Schema: PilarSalud; Owner: postgres
--

CREATE TABLE "PilarSalud"."Indica" (
    "Id_Indicacion" integer NOT NULL,
    "Id_Receta" integer,
    "Id_Medicamento" integer,
    "PrecioMedicamento" integer
);


ALTER TABLE "PilarSalud"."Indica" OWNER TO postgres;

--
-- Name: Indica_Id_Indicacion_seq; Type: SEQUENCE; Schema: PilarSalud; Owner: postgres
--

ALTER TABLE "PilarSalud"."Indica" ALTER COLUMN "Id_Indicacion" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "PilarSalud"."Indica_Id_Indicacion_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Localidad; Type: TABLE; Schema: PilarSalud; Owner: postgres
--

CREATE TABLE "PilarSalud"."Localidad" (
    "Id_Localidad" integer NOT NULL,
    "NombreLocalidad" character varying,
    "CP" character varying
);


ALTER TABLE "PilarSalud"."Localidad" OWNER TO postgres;

--
-- Name: Localidad_Id_Localidad_seq; Type: SEQUENCE; Schema: PilarSalud; Owner: postgres
--

ALTER TABLE "PilarSalud"."Localidad" ALTER COLUMN "Id_Localidad" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "PilarSalud"."Localidad_Id_Localidad_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Medicamento; Type: TABLE; Schema: PilarSalud; Owner: postgres
--

CREATE TABLE "PilarSalud"."Medicamento" (
    "Id_Medicamento" integer NOT NULL,
    "NombreMedicamento" character varying,
    "PrecioActual" integer
);


ALTER TABLE "PilarSalud"."Medicamento" OWNER TO postgres;

--
-- Name: Medicamento_Id_Medicamento_seq; Type: SEQUENCE; Schema: PilarSalud; Owner: postgres
--

ALTER TABLE "PilarSalud"."Medicamento" ALTER COLUMN "Id_Medicamento" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "PilarSalud"."Medicamento_Id_Medicamento_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Medico; Type: TABLE; Schema: PilarSalud; Owner: postgres
--

CREATE TABLE "PilarSalud"."Medico" (
    "Documento" integer NOT NULL,
    "Nombre" character varying,
    "Apellido" character varying
);


ALTER TABLE "PilarSalud"."Medico" OWNER TO postgres;

--
-- Name: MotivoCancelacion; Type: TABLE; Schema: PilarSalud; Owner: postgres
--

CREATE TABLE "PilarSalud"."MotivoCancelacion" (
    "Id_Motivo" integer NOT NULL,
    "NombreMotivo" character varying
);


ALTER TABLE "PilarSalud"."MotivoCancelacion" OWNER TO postgres;

--
-- Name: MotivoCancelacion_Id_Motivo_seq; Type: SEQUENCE; Schema: PilarSalud; Owner: postgres
--

ALTER TABLE "PilarSalud"."MotivoCancelacion" ALTER COLUMN "Id_Motivo" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "PilarSalud"."MotivoCancelacion_Id_Motivo_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Paciente; Type: TABLE; Schema: PilarSalud; Owner: postgres
--

CREATE TABLE "PilarSalud"."Paciente" (
    "Nro_Documento" integer NOT NULL,
    "Id_Localidad" integer,
    "Nombre" character varying,
    "Apellido" character varying,
    "FechaNacimiento" integer,
    "TieneOS" boolean
);


ALTER TABLE "PilarSalud"."Paciente" OWNER TO postgres;

--
-- Name: Pago; Type: TABLE; Schema: PilarSalud; Owner: postgres
--

CREATE TABLE "PilarSalud"."Pago" (
    "Id_Pago" integer NOT NULL,
    "Id_Receta" integer,
    "Id_FechaPago" integer,
    "Monto" integer
);


ALTER TABLE "PilarSalud"."Pago" OWNER TO postgres;

--
-- Name: Pago_Id_Pago_seq; Type: SEQUENCE; Schema: PilarSalud; Owner: postgres
--

ALTER TABLE "PilarSalud"."Pago" ALTER COLUMN "Id_Pago" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "PilarSalud"."Pago_Id_Pago_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Receta; Type: TABLE; Schema: PilarSalud; Owner: postgres
--

CREATE TABLE "PilarSalud"."Receta" (
    "Id_Receta" integer NOT NULL,
    "Id_FechaReceta" integer
);


ALTER TABLE "PilarSalud"."Receta" OWNER TO postgres;

--
-- Name: Receta_Id_Receta_seq; Type: SEQUENCE; Schema: PilarSalud; Owner: postgres
--

ALTER TABLE "PilarSalud"."Receta" ALTER COLUMN "Id_Receta" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "PilarSalud"."Receta_Id_Receta_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Turnos; Type: TABLE; Schema: PilarSalud; Owner: postgres
--

CREATE TABLE "PilarSalud"."Turnos" (
    "Id_Turno" integer NOT NULL,
    "Id_Paciente" integer,
    "Id_EspMedico" integer,
    "Id_Dependencia" integer,
    "FechaTurno" integer,
    "FechaAtencion" integer,
    "FechaSolicitud" integer,
    "Id_Motivo" integer,
    "Id_Receta" integer,
    "EstadoTurno" character varying,
    "HoraTurno" time with time zone,
    "HoraAtencion" time with time zone
);


ALTER TABLE "PilarSalud"."Turnos" OWNER TO postgres;

--
-- Name: Turnos_Id_Turno_seq; Type: SEQUENCE; Schema: PilarSalud; Owner: postgres
--

ALTER TABLE "PilarSalud"."Turnos" ALTER COLUMN "Id_Turno" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "PilarSalud"."Turnos_Id_Turno_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Dependencia Dependencia_pkey; Type: CONSTRAINT; Schema: PilarSalud; Owner: postgres
--

ALTER TABLE ONLY "PilarSalud"."Dependencia"
    ADD CONSTRAINT "Dependencia_pkey" PRIMARY KEY ("Id_Dependencia");


--
-- Name: EspecialidadMedico EspecialidadMedico_pkey; Type: CONSTRAINT; Schema: PilarSalud; Owner: postgres
--

ALTER TABLE ONLY "PilarSalud"."EspecialidadMedico"
    ADD CONSTRAINT "EspecialidadMedico_pkey" PRIMARY KEY ("Id_EspMedico");


--
-- Name: Especialidad Especialidad_pkey; Type: CONSTRAINT; Schema: PilarSalud; Owner: postgres
--

ALTER TABLE ONLY "PilarSalud"."Especialidad"
    ADD CONSTRAINT "Especialidad_pkey" PRIMARY KEY ("Id_Especialidad");


--
-- Name: Fecha Fecha_pkey; Type: CONSTRAINT; Schema: PilarSalud; Owner: postgres
--

ALTER TABLE ONLY "PilarSalud"."Fecha"
    ADD CONSTRAINT "Fecha_pkey" PRIMARY KEY ("Id_Fecha");


--
-- Name: Indica Indica_pkey; Type: CONSTRAINT; Schema: PilarSalud; Owner: postgres
--

ALTER TABLE ONLY "PilarSalud"."Indica"
    ADD CONSTRAINT "Indica_pkey" PRIMARY KEY ("Id_Indicacion");


--
-- Name: Localidad Localidad_pkey; Type: CONSTRAINT; Schema: PilarSalud; Owner: postgres
--

ALTER TABLE ONLY "PilarSalud"."Localidad"
    ADD CONSTRAINT "Localidad_pkey" PRIMARY KEY ("Id_Localidad");


--
-- Name: Medicamento Medicamento_pkey; Type: CONSTRAINT; Schema: PilarSalud; Owner: postgres
--

ALTER TABLE ONLY "PilarSalud"."Medicamento"
    ADD CONSTRAINT "Medicamento_pkey" PRIMARY KEY ("Id_Medicamento");


--
-- Name: Medico Medico_pkey; Type: CONSTRAINT; Schema: PilarSalud; Owner: postgres
--

ALTER TABLE ONLY "PilarSalud"."Medico"
    ADD CONSTRAINT "Medico_pkey" PRIMARY KEY ("Documento");


--
-- Name: MotivoCancelacion Motivo_pkey; Type: CONSTRAINT; Schema: PilarSalud; Owner: postgres
--

ALTER TABLE ONLY "PilarSalud"."MotivoCancelacion"
    ADD CONSTRAINT "Motivo_pkey" PRIMARY KEY ("Id_Motivo");


--
-- Name: Paciente Paciente_pkey; Type: CONSTRAINT; Schema: PilarSalud; Owner: postgres
--

ALTER TABLE ONLY "PilarSalud"."Paciente"
    ADD CONSTRAINT "Paciente_pkey" PRIMARY KEY ("Nro_Documento");


--
-- Name: Pago Pago_pkey; Type: CONSTRAINT; Schema: PilarSalud; Owner: postgres
--

ALTER TABLE ONLY "PilarSalud"."Pago"
    ADD CONSTRAINT "Pago_pkey" PRIMARY KEY ("Id_Pago");


--
-- Name: Receta Receta_pkey; Type: CONSTRAINT; Schema: PilarSalud; Owner: postgres
--

ALTER TABLE ONLY "PilarSalud"."Receta"
    ADD CONSTRAINT "Receta_pkey" PRIMARY KEY ("Id_Receta");


--
-- Name: Turnos Turnos_pk; Type: CONSTRAINT; Schema: PilarSalud; Owner: postgres
--

ALTER TABLE ONLY "PilarSalud"."Turnos"
    ADD CONSTRAINT "Turnos_pk" PRIMARY KEY ("Id_Turno");


--
-- Name: Turnos FK_Dependencia; Type: FK CONSTRAINT; Schema: PilarSalud; Owner: postgres
--

ALTER TABLE ONLY "PilarSalud"."Turnos"
    ADD CONSTRAINT "FK_Dependencia" FOREIGN KEY ("Id_Dependencia") REFERENCES "PilarSalud"."Dependencia"("Id_Dependencia");


--
-- Name: EspecialidadMedico FK_Especialidad; Type: FK CONSTRAINT; Schema: PilarSalud; Owner: postgres
--

ALTER TABLE ONLY "PilarSalud"."EspecialidadMedico"
    ADD CONSTRAINT "FK_Especialidad" FOREIGN KEY ("Id_Especialidad") REFERENCES "PilarSalud"."Especialidad"("Id_Especialidad");


--
-- Name: Paciente FK_Fecha; Type: FK CONSTRAINT; Schema: PilarSalud; Owner: postgres
--

ALTER TABLE ONLY "PilarSalud"."Paciente"
    ADD CONSTRAINT "FK_Fecha" FOREIGN KEY ("FechaNacimiento") REFERENCES "PilarSalud"."Fecha"("Id_Fecha");


--
-- Name: Pago FK_Fecha; Type: FK CONSTRAINT; Schema: PilarSalud; Owner: postgres
--

ALTER TABLE ONLY "PilarSalud"."Pago"
    ADD CONSTRAINT "FK_Fecha" FOREIGN KEY ("Id_FechaPago") REFERENCES "PilarSalud"."Fecha"("Id_Fecha");


--
-- Name: Receta FK_FechaReceta; Type: FK CONSTRAINT; Schema: PilarSalud; Owner: postgres
--

ALTER TABLE ONLY "PilarSalud"."Receta"
    ADD CONSTRAINT "FK_FechaReceta" FOREIGN KEY ("Id_FechaReceta") REFERENCES "PilarSalud"."Fecha"("Id_Fecha");


--
-- Name: Turnos FK_FechaSolicitud; Type: FK CONSTRAINT; Schema: PilarSalud; Owner: postgres
--

ALTER TABLE ONLY "PilarSalud"."Turnos"
    ADD CONSTRAINT "FK_FechaSolicitud" FOREIGN KEY ("FechaSolicitud") REFERENCES "PilarSalud"."Fecha"("Id_Fecha");


--
-- Name: Dependencia FK_Localidad; Type: FK CONSTRAINT; Schema: PilarSalud; Owner: postgres
--

ALTER TABLE ONLY "PilarSalud"."Dependencia"
    ADD CONSTRAINT "FK_Localidad" FOREIGN KEY ("Id_Localidad") REFERENCES "PilarSalud"."Localidad"("Id_Localidad");


--
-- Name: Paciente FK_Localidad; Type: FK CONSTRAINT; Schema: PilarSalud; Owner: postgres
--

ALTER TABLE ONLY "PilarSalud"."Paciente"
    ADD CONSTRAINT "FK_Localidad" FOREIGN KEY ("Id_Localidad") REFERENCES "PilarSalud"."Localidad"("Id_Localidad");


--
-- Name: Indica FK_Medicamento; Type: FK CONSTRAINT; Schema: PilarSalud; Owner: postgres
--

ALTER TABLE ONLY "PilarSalud"."Indica"
    ADD CONSTRAINT "FK_Medicamento" FOREIGN KEY ("Id_Medicamento") REFERENCES "PilarSalud"."Medicamento"("Id_Medicamento");


--
-- Name: EspecialidadMedico FK_Medico; Type: FK CONSTRAINT; Schema: PilarSalud; Owner: postgres
--

ALTER TABLE ONLY "PilarSalud"."EspecialidadMedico"
    ADD CONSTRAINT "FK_Medico" FOREIGN KEY ("Documento") REFERENCES "PilarSalud"."Medico"("Documento");


--
-- Name: Turnos FK_Medico; Type: FK CONSTRAINT; Schema: PilarSalud; Owner: postgres
--

ALTER TABLE ONLY "PilarSalud"."Turnos"
    ADD CONSTRAINT "FK_Medico" FOREIGN KEY ("Id_EspMedico") REFERENCES "PilarSalud"."EspecialidadMedico"("Id_EspMedico");


--
-- Name: Turnos FK_Motivo; Type: FK CONSTRAINT; Schema: PilarSalud; Owner: postgres
--

ALTER TABLE ONLY "PilarSalud"."Turnos"
    ADD CONSTRAINT "FK_Motivo" FOREIGN KEY ("Id_Motivo") REFERENCES "PilarSalud"."MotivoCancelacion"("Id_Motivo");


--
-- Name: Turnos FK_Paciente; Type: FK CONSTRAINT; Schema: PilarSalud; Owner: postgres
--

ALTER TABLE ONLY "PilarSalud"."Turnos"
    ADD CONSTRAINT "FK_Paciente" FOREIGN KEY ("Id_Paciente") REFERENCES "PilarSalud"."Paciente"("Nro_Documento");


--
-- Name: Indica FK_Receta; Type: FK CONSTRAINT; Schema: PilarSalud; Owner: postgres
--

ALTER TABLE ONLY "PilarSalud"."Indica"
    ADD CONSTRAINT "FK_Receta" FOREIGN KEY ("Id_Receta") REFERENCES "PilarSalud"."Receta"("Id_Receta");


--
-- Name: Pago FK_Receta; Type: FK CONSTRAINT; Schema: PilarSalud; Owner: postgres
--

ALTER TABLE ONLY "PilarSalud"."Pago"
    ADD CONSTRAINT "FK_Receta" FOREIGN KEY ("Id_Receta") REFERENCES "PilarSalud"."Receta"("Id_Receta");


--
-- Name: Turnos FK_Receta; Type: FK CONSTRAINT; Schema: PilarSalud; Owner: postgres
--

ALTER TABLE ONLY "PilarSalud"."Turnos"
    ADD CONSTRAINT "FK_Receta" FOREIGN KEY ("Id_Receta") REFERENCES "PilarSalud"."Receta"("Id_Receta");


--
-- PostgreSQL database dump complete
--

